### PR TITLE
bump mongoose version to 5.0

### PR DESCRIPTION
**Pull request by hardywu**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

### CODE REVIEW

**Comment by thonatos** [comment]
@popomore 

老板来发版呀~

**Comment by popomore** [comment]
break?

**Comment by popomore** [comment]
搞定另外两个 pr？

**Comment by thonatos** [comment]
emmmm

**Comment by hsiaosiyuan0** [comment]
要不不能另外俩 pr 了？毕竟这个问题比较紧急 https://github.com/Automattic/mongoose/issues/5574

**Comment by hardywu** [comment]
@hsiaosiyuan0 你可以先暂时用 hardywu:master 做安装源

**Comment by hsiaosiyuan0** [comment]
@hardywu 谢谢，我用了自己的 fork 了，我已经两个官方的插件都用了自己的 fork 了，真忧伤

**Comment by popomore** [comment]
+ egg-mongoose@3.0.0

**Pull request merged**
