### PR TITLE
chore: TypeScript support

### PR DESCRIPTION
**Pull request by BaffinLee**
##### Checklist

- [x] `npm test` passes
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message follows commit guidelines

##### Description of change

Add `index.d.ts file` to support TypeScript.

### CODE REVIEW

**Comment by BaffinLee** [comment]
@atian25 @whxaxes Ready to merge?

**Comment by atian25** [comment]
@eggjs/core who's online, please publish

**Comment by atian25** [comment]
```bash
➜  npm owner ls egg-mongoose
dead_horse <dead_horse@qq.com>
eggjs <fengmk2+eggjs@gmail.com>
fengmk2 <fengmk2@gmail.com>
jtyjty99999 <jtyjty99999@126.com>
popomore <sakura9515@gmail.com>
```

@popomore @dead-horse 发下版本

**Comment by popomore** [comment]
+ egg-mongoose@3.1.0

**Comment by zhaojunlike** [comment]
Could you please tell me how I should use the index.d.ts file in egg-mongoose if I want to use typescript and finally merge it into index.d.ts in eggjs?

**Comment by BaffinLee** [comment]
If you use `egg-mongoose` in `eggjs` project, just follow the official [docs](https://eggjs.org/zh-cn/tutorials/typescript.html), the `index.d.ts` will be merged automatically.

**Pull request merged**
