### PR TITLE
feat: update mongoose's version to be compatable with typescript schemas (Nodejs >=14.x), with Egg>=3.x

### PR DESCRIPTION
**Pull request by Wai-Dung**
Mongoose's version update Reason：

1、https://github.com/eggjs/egg/issues/5190
2、https://mongoosejs.com/docs/migrating_to_6.html#version-requirements

image

Notice：This upgrade is a big change，it upgrades nodejs to 14.x at least, with the mongodb to 6.x (supporting the latest TypeScripts).

### CODE REVIEW

**Comment by MaledongGit** [comment]
@JasinYip ：Can u help to merge it so as to upgrade the version mongoose?

**Comment by MaledongGit** [comment]
@fengmk2 , @atian25 ：Can u help to upgrade it to the latest version with the GitHub Actions test?
The plugin is too old to use :(

**Comment by MQpeng** [comment]
Merged the PR：https://www.npmjs.com/package/@tonyer/egg-mongoose

**Comment by Wai-Dung** [comment]
@MQpeng ：Already merged?

**Comment by MQpeng** [comment]
@Wai-Dung Yes! However, there were some bugs during the migration of my project, so I rolled back to the official version

**Review by fengmk2 — APPROVED** [review]
LGTM

I remove the package-lock.json file from the commit.

**Comment by trylovetom** [comment]
@fengmk2 善意提醒，這隻 PR 似乎沒有通過覆蓋率測試就被合併了！

**Pull request merged**
